version: '3.8'

services:

  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis

  redis: 
    image: redislabs/redismod
    container_name: redis
    ports:
      - '6379:6379'
